services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        #bind:

    Markocupic\NotificationCenterEmailBundle\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection,Resources}
